---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux64:
    platforms:
      - Linux64
    types:
      opt:
        task: tasks/builds/opt_linux64.yml
      debug:
        task: tasks/builds/dbg_linux64.yml

tests:
  crashtest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_crashtest_e10s_dbg.yml
  jsreftest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_jsreftest_e10s_dbg.yml
  marionette-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_marionette_e10s_dbg.yml
  mochitest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_plain_e10s_dbg.yml
  mochitest-browser-chrome-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_bc_e10s_dbg.yml
  mochitest-devtools-chrome-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_dt_e10s_dbg.yml
  mochitest-media-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_media_e10s_dbg.yml
  mochitest-webgl-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_mochitest_gl_e10s_dbg.yml
  reftest-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_e10s_dbg.yml
  reftest-no-accel-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_not_accelerated_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_reftest_not_accelerated_e10s_dbg.yml
  web-platform-tests-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_e10s_dbg.yml
  web-platform-tests-reftests-e10s:
    allowed_build_tasks:
      tasks/builds/opt_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s_opt.yml
      tasks/builds/dbg_linux64.yml:
        task: tasks/tests/fx_linux64_web_platform_tests_reftests_e10s_dbg.yml
