$inherits:
  from: 'tasks/build.yml'


task:
  workerType: b2gbuild

  routes:
    - 'index.gecko.v1.{{project}}.revision.linux.{{head_rev}}.{{build_name}}.{{build_type}}'
    - 'index.gecko.v1.{{project}}.latest.linux.{{build_name}}.{{build_type}}'

  scopes:
    # docker build tasks use tc-vcs so include the scope.
    - 'docker-worker:cache:level-{{level}}-{{project}}-tc-vcs'

  payload:

    cache:
      level-{{level}}-{{project}}-tc-vcs: '/home/worker/.tc-vcs'

    # All docker builds share a common artifact directory for ease of uploading.
    artifacts:
      'public/build':
        type: directory
        path: '/home/worker/artifacts/'
        expires: '{{#from_now}}1 year{{/from_now}}'
