# This is the "base" task which contains the common values all linting tests must
# provide.
---
taskId: {{build_slugid}}

task:
  created:
    relative-datestamp: '0 seconds'
  deadline:
    relative-datestamp: '24 hours'
  metadata:
    source: http://todo.com/soon
    owner: mozilla-taskcluster-maintenance@mozilla.com

  tags:
    createdForUser: {{owner}}

  workerType: b2gtest
  provisionerId: aws-provisioner-v1
  schedulerId: task-graph-scheduler

  routes:
    - 'index.gecko.v1.{{project}}.revision.linux.{{head_rev}}.{{build_name}}'
    - 'index.gecko.v1.{{project}}.latest.linux.{{build_name}}'
  scopes:
    - 'docker-worker:cache:level-{{level}}-hg-shared'
    - 'docker-worker:cache:level-{{level}}-workspace'

  payload:
    # Thirty minutes should be enough for lint checks
    maxRunTime: 1800

    cache:
      level-{{level}}-hg-shared: '/home/worker/hg-shared'
      level-{{level}}-workspace: '/home/worker/workspace'

    env:
      GECKO_BASE_REPOSITORY: '{{base_repository}}'
      GECKO_HEAD_REPOSITORY: '{{head_repository}}'
      GECKO_HEAD_REV: '{{head_rev}}'

  extra:
    build_product: '{{build_product}}'
    build_name: {{build_name}}
    build_type: {{build_type}}
    index:
      rank: {{rank}}
    treeherder:
      jobKind: test
