# This task is the base for most tests in gecko.
docker-image: tester
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: '{{source}}'
    owner: mozilla-taskcluster-maintenance@mozilla.com
  tags:
    createdForUser: {{owner}}
  workerType: b2gtest
  provisionerId: aws-provisioner-v1
  schedulerId: task-graph-scheduler

  scopes:
    - 'docker-worker:feature:allowPtrace'

  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId:
        task-reference: "<docker-image>"

    maxRunTime: 3600
    env:
      MOZILLA_BUILD_URL: {"task-reference": "https://queue.taskcluster.net/v1/task/<{{build_slugid}}>/artifacts/{{build_location}}"}
      MOZHARNESS_URL: {"task-reference": "https://queue.taskcluster.net/v1/task/<{{build_slugid}}>/artifacts/{{mozharness_location}}"}

    # All builds share a common artifact directory for ease of uploading.
    artifacts:
      'public/logs/':
        type: directory
        path: '/home/worker/workspace/build/upload/logs/'
        expires: '{{#from_now}}1 year{{/from_now}}'
      'public/test_info/':
        type: directory
        path: '/home/worker/workspace/build/blobber_upload_dir/'
        expires: '{{#from_now}}1 year{{/from_now}}'

  extra:
    chunks:
      total: 1
      current: {{chunk}}
    treeherder:
      jobKind: test
      groupSymbol: tc
      groupName: Submitted by taskcluster
