$inherits:
  from: 'tasks/build.yml'

task:
  workerType: win2012
  payload:
    artifacts:
      -
        type: 'directory'
        path: 'public\build'
        expires: '{{#from_now}}1 year{{/from_now}}'
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      jobKind: build
      machine:
        # https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: {{platform}}
