---
# List of all possible flags for each category of tests used in the case where
# "all" is specified.
flags:
  builds:
    - linux32_gecko  # b2g desktop linux 32 bit
    - linux64_gecko  # b2g desktop linux 64 bit
    - linux64-mulet  # Firefox desktop - b2g gecko linux 64 bit
    - linux64-haz    # Firefox desktop browser, rooting hazard analysis
    - linux64-shell-haz  # JS shell, rooting hazard analysis
    - linux64-mulet-haz  # Firefox desktop - b2g gecko linux 64 bit, rooting hazard analysis
    - macosx64_gecko # b2g desktop osx 64 bit
    - win32_gecko    # b2g desktop win 32 bit
    - nexus-5l-eng
    - aries
    - aries-eng
    - android-api-15
    - android-api-15-frontend
    - android-partner-sample1
    - linux
    - linux64
    - linux64-st-an
    - linux64-artifact
    - linux64-asan
    - linux64-pgo
    - linux64-valgrind
    - macosx64
    - macosx64-st-an

  tests:
    - cppunit
    - crashtest
    - crashtest-e10s
    - external-media-tests
    - firefox-ui-functional
    - firefox-ui-functional-e10s
    - gaia-build
    - gaia-build-unit
    - gaia-js-integration
    - gaia-linter
    - gaia-unit
    - gaia-unit-oop
    - gtest
    - jittests
    - jsreftest
    - jsreftest-e10s
    - luciddream
    - marionette
    - marionette-e10s
    - marionette-webapi
    - mochitest
    - mochitest-a11y
    - mochitest-browser-chrome
    - mochitest-browser-chrome-e10s
    - mochitest-chrome
    - mochitest-devtools-chrome
    - mochitest-devtools-chrome-e10s
    - mochitest-e10s
    - mochitest-jetpack
    - mochitest-media
    - mochitest-media-e10s
    - mochitest-webgl
    - mochitest-webgl-e10s
    - mochitest-gpu
    - mochitest-gpu-e10s
    - mochitest-clipboard
    - mochitest-clipboard-e10s
    - mochitest-valgrind
    - mozmill
    - reftest
    - reftest-e10s
    - reftest-no-accel
    - reftest-no-accel-e10s
    - web-platform-tests
    - web-platform-tests-e10s
    - web-platform-tests-reftests
    - web-platform-tests-reftests-e10s
    - xpcshell
