$inherits:
  from: 'tasks/builds/b2g_phone_base.yml'
task:
  workerType: flame-kk

  payload:
    env:
      DEBUG: 0
      VARIANT: eng
      GAIA_OPTIMIZE: '1'
      B2G_SYSTEM_APPS: '1'
      MOZ_TELEMETRY_REPORTING: '1'
      MOZ_CRASHREPORTER_NO_REPORT: '1'
      GAIA_KEYBOARD_LAYOUTS: 'en,pt-BR,es,de,fr,pl,zh-Hans-Pinyin,zh-Hant-Zhuyin,en-Dvorak'
      B2G_UPDATE_CHANNEL: 'default'
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
