$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'nexus-5-l-eng'
    build_type: 'opt'
task:
  workerType: flame-kk
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-nexus-5-l-eng'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-nexus-5-l-eng-objdir-gecko'
  metadata:
    name: '[TC] B2G Nexus 5-L Eng'
  payload:
    cache:
      level-{{level}}-{{project}}-build-nexus-5-l-eng: /home/worker/object-folder
      level-{{level}}-{{project}}-build-nexus-5-l-eng-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'nexus-5-l'
      DEBUG: 0
    command:
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/taskcluster/scripts/phone-builder &&
        buildbot_step 'Build' ./build-phone.sh $HOME/workspace
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: Be
      groupSymbol: Nexus 5-L
      groupName: Nexus 5-L Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/nexus-5-l.zip'
