$inherits:
  from: 'tasks/builds/b2g_phone_eng_base.yml'
  variables:
    build_name: 'aries-eng'
    build_type: 'opt'
task:
  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-eng'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-aries-eng-objdir-gecko'
  metadata:
    name: '[TC] B2G Aries Eng'

  payload:
    cache:
      level-{{level}}-{{project}}-build-aries-eng: /home/worker/workspace
      level-{{level}}-{{project}}-build-aries-eng-objdir-gecko: /home/worker/objdir-gecko
    env:
      TARGET: 'aries'
      MOZHARNESS_CONFIG: b2g/taskcluster-phone-eng.py
  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      symbol: Be
      groupSymbol: Aries
      groupName: Aries Device Image
      machine:
        platform: b2g-device-image
    locations:
      img: 'private/build/aries.zip'
