$inherits:
  from: 'tasks/docker_build.yml'
  variables:
    build_product: 'b2g'
docker-image: builder
task:
  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId:
        task-reference: "<docker-image>"
  extra:
    locations:
      test_packages: 'public/build/target.test_packages.json'
      mozharness: 'public/build/mozharness.zip'
