$inherits:
  from: 'tasks/builds/firefox_docker_base.yml'
task:

  scopes:
    - 'docker-worker:cache:tooltool-cache'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-{{build_name}}-workspace'
    - 'docker-worker:relengapi-proxy:tooltool.download.internal'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'

  routes:
    - 'index.buildbot.branches.{{project}}.{{build_name}}'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.{{build_name}}'

  payload:
    cache:
      tooltool-cache: '/home/worker/tooltool-cache'
      level-{{level}}-{{project}}-build-{{build_name}}-workspace: '/home/worker/workspace'

    features:
      relengAPIProxy: true

    env:
      MOZHARNESS_SCRIPT: 'mozharness/scripts/fx_desktop_build.py'
      MOZHARNESS_CONFIG: 'builds/releng_base_mac_64_cross_builds.py balrog/production.py'
      MOZHARNESS_ACTIONS: 'get-secrets build generate-build-stats update'
      MH_BRANCH: {{project}}
      MH_BUILD_POOL: taskcluster
      # image paths
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'

    maxRunTime: 36000

    command: ["/bin/bash", "bin/build.sh"]

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: osx-10-7
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.dmg'
      tests: 'public/build/target.tests.zip'

