$inherits:
  from: 'tasks/builds/base_linux32.yml'
  variables:
    build_name: 'linux32'
    build_type: 'dbg'
task:
  metadata:
      name: '[TC] Linux32 Dbg'
      description: 'Linux32 Dbg'

  routes:
    - 'coalesce.v1.builds.{{project}}.dbg_linux32'

  workerType: dbg-linux32

  payload:
    supersederUrl: 'https://coalesce.mozilla-releng.net/v1/list/builds.{{project}}.dbg_linux32'

    env:
      MH_CUSTOM_BUILD_VARIANT_CFG: 'debug'

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B
      collection:
        debug: true

