$inherits:
  from: 'tasks/builds/firefox_docker_base.yml'
  variables:
    build_name: 'linux64-gcc'
    build_type: 'opt'
task:
  metadata:
    name: '[TC] GCC'
    description: 'GCC'

  workerType: opt-linux64

  routes:
    - 'index.buildbot.branches.{{project}}.gcc'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.gcc'

  payload:
    env:
      MOZHARNESS_DISABLE: 'true'
      TOOLS_DISABLE: 'true'

    maxRunTime: 36000

    command: ["/bin/bash", "-c", "cd /home/worker/ && ./bin/checkout-sources.sh && ./workspace/build/src/taskcluster/scripts/misc/build-gcc-linux.sh" ]

    artifacts:
      'public/gcc.tar.xz':
        type: file
        path: '/home/worker/workspace/artifacts/gcc.tar.xz'
        expires: '{{#from_now}}1 year{{/from_now}}'

  extra:
    treeherderEnv:
      - staging
      - production
    treeherder:
      groupSymbol: Cc
      groupName: Compilers, submitted by taskcluster
      symbol: GCC
      machine:
        platform: linux64
    locations:
        build: null
        tests: null
