$inherits:
  from: 'tasks/docker_build.yml'
  variables:
    build_product: 'mobile'
docker-image: desktop-build
task:
  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId:
        task-reference: "<docker-image>"

