$inherits:
  from: 'tasks/builds/b2g_base.yml'
  variables:
    build_name: 'mulet-haz'
    build_type: 'debug'
task:
  metadata:
    name: '[TC] Mulet Hazard Linux'
    description: Mulet Hazard Analysis Linux

  workerType: mulet-debug

  routes:
    - 'index.buildbot.branches.{{project}}.linux64-haz-mulet'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux64-haz-mulet'

  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-mulet-linux-workspace'
    - 'docker-worker:cache:tooltool-cache'
    - 'docker-worker:relengapi-proxy:tooltool.download.public'

  payload:
    cache:
      level-{{level}}-{{project}}-build-mulet-haz-linux-workspace: '/home/worker/workspace'
      tooltool-cache: '/home/worker/tools/tooltool-cache'

    features:
      relengAPIProxy: true

    env:
      MOZCONFIG: 'b2g/dev/config/mozconfigs/linux64/mulet-hazards'
      TOOLTOOL_MANIFEST: 'gecko/b2g/dev/config/tooltool-manifests/linux64/hazard.manifest'

    maxRunTime: 36000

    command:
      - /bin/bash
      - -c
      - >
        checkout-gecko workspace &&
        cd ./workspace/gecko/taskcluster/scripts/builder &&
        buildbot_step 'Build' ./build-mulet-haz-linux.sh $HOME/workspace

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      groupSymbol: "tc"
      symbol: "H"
      tier: 3
      machine:
        platform: mulet-linux64
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: null
      tests: null
