$inherits:
  from: 'tasks/builds/base_macosx64.yml'
  variables:
    build_name: 'macosx64-st-an'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] MacOSX64 Static Analysis Opt'
      description: 'MacOSX64 Static Analysis Opt'

  workerType: opt-macosx64

  payload:
    env:
      MH_CUSTOM_BUILD_VARIANT_CFG: 'cross-opt'
      DIST_UPLOADS: ''
      DIST_TARGET_UPLOADS: ''
  extra:
    treeherder:
      groupSymbol: "?"
      groupName: Submitted by taskcluster
      symbol: S
