$inherits:
  from: 'tasks/builds/base_linux64.yml'
  variables:
    build_name: 'linux64'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] Linux64 Opt'
      description: 'Linux64 Opt'

  routes:
    - 'index.buildbot.branches.{{project}}.linux64'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.linux64'

  workerType: opt-linux64

  extra:
    treeherder:
      groupSymbol: tc
      groupName: Submitted by taskcluster
      symbol: B

