$inherits:
  from: 'tasks/builds/base_macosx64.yml'
  variables:
    build_name: 'macosx64'
    build_type: 'opt'
task:
  metadata:
      name: '[TC] MacOSX64 Opt'
      description: 'MacOSX64 Opt'

  workerType: opt-macosx64
