$inherits:
  from: 'tasks/builds/sm_variant_base.yml'
  variables:
    build_name: 'sm-arm-sim'
    build_type: 'debug'
task:
  payload:
    env:
        SPIDERMONKEY_VARIANT: 'arm-sim'
  metadata:
    name: '[TC] Spidermonkey ARM sim'
    description: 'Spidermonkey ARM sim'
  extra:
    treeherder:
      symbol: arm
