$inherits:
  from: 'tasks/builds/sm_variant_base.yml'
  variables:
    build_name: 'sm-arm-sim-osx'
    build_type: 'debug'
task:
  payload:
    env:
      SPIDERMONKEY_VARIANT: 'arm-sim-osx'
  metadata:
    name: '[TC] Spidermonkey ARM Simulator OSX'
    description: 'Spidermonkey ARM Simulator OSX'
  extra:
    treeherder:
      symbol: arm
