$inherits:
  from: 'tasks/builds/firefox_docker_base.yml'
task:
  workerType: spidermonkey

  routes:
    - 'index.buildbot.branches.{{project}}.sm-plain'
    - 'index.buildbot.revisions.{{head_rev}}.{{project}}.sm-plain'

  scopes:
    - 'docker-worker:cache:tooltool-cache'
    - 'docker-worker:cache:level-{{level}}-{{project}}-build-spidermonkey-workspace'

  payload:
    cache:
      tooltool-cache: '/home/worker/tooltool-cache'
      level-{{level}}-{{project}}-build-spidermonkey-workspace: '/home/worker/workspace'

    env:
      MOZHARNESS_DISABLE: 'true'
      TOOLS_DISABLE: 'true'
      TOOLTOOL_CACHE: '/home/worker/tooltool-cache'

    maxRunTime: 36000

  extra:
    treeherderEnv:
      - staging
      - production
    treeherder:
      groupSymbol: SM-tc
      groupName: Spider Monkey, submitted by taskcluster
      machine:
        # see https://github.com/mozilla/treeherder/blob/master/ui/js/values.js
        platform: linux64
    # Rather then enforcing particular conventions we require that all build
    # tasks provide the "build" extra field to specify where the build and tests
    # files are located.
    locations:
      build: 'public/build/target.spidermonkey.tar.bz2'
      tests: 'public/build/target.spidermonkey.tar.bz2'
