$inherits:
  from: 'tasks/builds/sm_variant_base.yml'
  variables:
    build_name: 'sm-compacting'
    build_type: 'debug'
task:
  payload:
    env:
      SPIDERMONKEY_VARIANT: 'compacting'
  metadata:
    name: '[TC] Spidermonkey Compactng'
    description: 'Spidermonkey Compacting'
  extra:
    treeherder:
      symbol: cgc
