$inherits:
  from: 'tasks/builds/sm_base.yml'
  variables:
    build_name: 'sm-package'
    build_type: 'opt'
task:
  payload:
    env:
      SPIDERMONKEY_VARIANT: 'plain'

    command: [ "/bin/bash", "-c", "cd /home/worker/ && ./bin/checkout-sources.sh && ./workspace/build/src/taskcluster/scripts/builder/build-sm-package.sh" ]

  metadata:
    name: '[TC] Spidermonkey Package'
    description: 'Spidermonkey Package'
  extra:
    treeherder:
      symbol: pkg
