# This tasks takes a mulet build, pull gaia and craft a xpi file for FxOS simulator addon
---
taskId: {{build_slugid}}
docker-image: builder
task:
  created: '{{now}}'
  deadline: '{{#from_now}}24 hours{{/from_now}}'
  metadata:
    source: '{{source}}'
    owner: apoirot@mozilla.com
    name: '[TC] FxOS Simulator'
    description: 'Firefox OS Simulator addon'
  tags:
    createdForUser: {{owner}}

  workerType: b2gbuild
  provisionerId: aws-provisioner-v1
  schedulerId: task-graph-scheduler

  routes:
    - 'index.gecko.v1.{{project}}.latest.simulator.{{build_type}}'

  scopes:
    - 'docker-worker:cache:level-{{level}}-{{project}}-tc-vcs'

  payload:
    image:
      type: 'task-image'
      path: 'public/image.tar'
      taskId:
        task-reference: "<docker-image>"

    maxRunTime: 600

    command:
      - /bin/bash
      - -exc
      - task-reference: >
          tc-vcs checkout ./gecko {{base_repository}} {{head_repository}} {{head_rev}} {{head_ref}} &&
          ./gecko/testing/taskcluster/scripts/builder/pull-gaia.sh ./gecko ./gaia gaia_props.py &&
          ./gecko/testing/taskcluster/scripts/builder/build-simulator.sh ./gecko ./gaia
          https://queue.taskcluster.net/v1/task/<{{build_slugid}}>/artifacts/{{build_location}}

    artifacts:
      'public/build':
        type: directory
        path: '/home/worker/artifacts/'
        expires: '{{#from_now}}1 year{{/from_now}}'

    env:
      GECKO_BASE_REPOSITORY: '{{base_repository}}'
      GECKO_HEAD_REPOSITORY: '{{head_repository}}'
      GECKO_HEAD_REV: '{{head_rev}}'
      GECKO_HEAD_REF: '{{head_ref}}'

  extra:
    treeherderEnv:
      - production
      - staging
    treeherder:
      jobKind: build
      groupSymbol: tc-Sim
      groupName: Simulator build
      symbol: 'S'
