---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux64-mulet:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/mulet_linux.yml

tests:
  mochitest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_mochitests.yml
        chunks: 5
